= Aniseed (work in progress)

== Sweeter Neovim with Fennel

Write https://fennel-lang.org/[Fennel] code and have https://neovim.io/[Neovim] compile and execute it via Lua. Configure and control your Neovim through the wonders of Lisp!

This is mostly an experiment to see if I can replace my Neovim configuration in my https://github.com/Olical/dotfiles[dotfiles] as well as parts of https://github.com/Olical/conjure[Conjure] with Fennel.

Your code is compiled ahead of time into Lua only if it has changed since you last compiled it. Aniseed also provides a few helper functions which I find useful, you may too!

== TODO

 * [ ] Only re-compile if the source file is newer than the destination.
 * [ ] Give it a bug bash / dogfood with my own dotfiles.
 * [ ] Write some documentation.
 * [ ] Talk about this slightly silly experiment at https://oli.me.uk[oli.me.uk].

== Unlicenced

Find the full http://unlicense.org/[unlicense] in the `UNLICENSE` file, but here's a snippet.

____
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.
____
