= Aniseed

Aniseed bridges the gap between https://fennel-lang.org/[Fennel] (a Lisp that compiles to Lua) and https://neovim.io/[Neovim]. Allowing you to easily write plugins or configuration in a https://clojure.org/[Clojure]-like Lisp with great runtime performance.

https://asciinema.org/a/326401[image:https://asciinema.org/a/326401.svg[asciicast]]

Further documentation can be found in link:doc/aniseed.txt[`:help aniseed`].

== Installation

Use your favourite plugin manager, I recommend https://github.com/junegunn/vim-plug[vim-plug] if you don't have one already.

[source,viml]
----
Plug 'Olical/aniseed', { 'tag': 'v3.3.0' }
Plug 'bakpakin/fennel.vim'
----

For interactive evaluation you need to install https://github.com/Olical/conjure[Conjure]. It'll allow you to send portions of your code off for evaluation as well as see the results in an interactive log buffer.

You may also be interested in https://github.com/Olical/nvim-local-fennel[nvim-local-fennel] which is essentially a Fennel based version of https://github.com/embear/vim-localvimrc[localvimrc].

== Standard library

Aniseed provides a fair few functions that it uses internally but are designed for use by plugin authors. The best way to discover these is to delve into `fnl/aniseed` and have a look through the source, anything that isn't self explanatory has a documentation string attached to it.

[source,clojure]
----
(module foo
  {require {a aniseed.core
            str aniseed.string}})

(defn- add [a b]
  (+ a b))

(->> [1 2 3]
     (a.map a.inc)
     (a.reduce add 0))
;; => 9

(str.join ", " [1 2 3])
;; => "1, 2, 3"
----

And here's some more useful modules you'll probably want to check out.

 * `aniseed.nvim` is actually https://github.com/norcalli/nvim.lua[nvim.lua], an extremely helpful library for controlling Neovim with a more expressive syntax.
 * `aniseed.eval` allows you to run more Fennel code through Aniseed.
 * `aniseed.compile` lets you compile strings and files of Fennel into Lua.

== Unlicenced

The following files are excluded from my license and ownership:

 * `lua/aniseed/deps/fennel.lua`
 * `lua/aniseed/deps/fennelview.lua`
 * `lua/aniseed/deps/nvim.lua`

These files come from https://fennel-lang.org/[Fennel] and https://github.com/norcalli/nvim.lua[nvim.lua], *I did not write them*, all other files are from me and unlicenced. The aforementioned files should be considered under their respective project licences. They are copied into this repo to allow the plugin to work with systems that don't support symlinks correctly.

Find the full http://unlicense.org/[unlicense] in the `UNLICENSE` file, but here's a snippet.

____
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.
____
