= Aniseed

Easily write configuration or plugins for https://neovim.io/[Neovim] in https://fennel-lang.org/[Fennel], a Lisp that compiles to Lua.

This is aimed at people who want to extend Neovim interactively with a Lisp as you would in some _other_ text editor. Code is evaluated interactively as you work, it feels a lot like editing https://clojure.org/[Clojure] with https://github.com/Olical/conjure[Conjure].

It provides the tools you need to compile, run and test (even in CI!) Fennel within your editor. It includes a set of macros to make defining and depending on modules far more like Clojure than Lua. No more remembering to put values in a table at the bottom of the file!

TODO stdlib docs

[source,clojure]
----
(module my-module
  {;; Require other modules with aliases.
   require {core aniseed.core
            nvim aniseed.nvim}

   ;; Inline modules at compile time.
   include {some-dep my-other.dependency}})

(def- some-private-value 2)

(defn- some-private-fn [x]
  (* x some-private-value))

(defn a-public-fn [x]
  (-> x
      (some-private-fn)
      (core.inc)))

(comment
  (a-public-fn 10) ;; => 21
  (some-private-fn 10) ;; => 20
  (set nvim.g.hello "world!"))
----

Aniseed allows you to evaluate any form in this source code to build up your module dynamically with a constant REPL based flow. Once the buffer, file or forms have been evaluated you can even call the function from Lua and Vim Script.

[source,viml]
----
lua print(require("my-module")["a-public-fn"](10))
" Prints: 21

echo g:hello
" Prints: world!
----

https://github.com/Olical/nvim-local-fennel[nvim-local-fennel] is an example of what you can do with Aniseed, it allows you to write machine or directory specific configuration in Fennel. It's useful in it's own right but also a good reference for how to write a plugin.

== Installation

Use your favourite plugin manager, I recommend https://github.com/junegunn/vim-plug[vim-plug] if you don't have one already.

[source,viml]
----
" Depend on the latest version via tag.
Plug 'Olical/aniseed', { 'tag': 'v3.0.0' }

" For Fennel highlighting (based on Clojure).
Plug 'bakpakin/fennel.vim'

" Used by the evaluation mappings.
Plug 'guns/vim-sexp'

" Highly recommended if you're going to use vim-sexp.
Plug 'tpope/vim-sexp-mappings-for-regular-people'

" Set up the Aniseed commands and mappings.
lua require('aniseed.mapping').init()
----

The reliance on `vim-sexp` will be replaced by integration with https://github.com/Olical/conjure[Conjure] once I've finished rewriting it with Aniseed. Conjure, with the help of Aniseed, will become a generic suite for working with Lisps in Neovim.

== Use case 1: Writing your dotfiles in Fennel

My Neovim https://github.com/Olical/dotfiles/tree/master/neovim/.config/nvim[dotfiles] are written in Fennel using Aniseed, all you need to do is add the following to your `init.vim` after Aniseed has been loaded.

[source,viml]
----
lua require('aniseed.dotfiles')
----

Now try adding some Fennel such as the example below to `~/.config/nvim/fnl/dotfiles/init.fnl`. The next time you open Neovim you'll see `"Hello!"` printed as a message!

[source,clojure]
----
(module dotfiles.init
  {require {core aniseed.core}})

(core.pr "Hello!")
----

This will write the compiled Lua into `~/.config/nvim/lua`, it's only recompiled if the Fennel changes. You'll want to add the `lua` directory to your `.gitignore` if your dotfiles are in git.

You can continue to add more files under `fnl/dotfiles` and require them using the `module` macro syntax.

== Use case 2: Compiling a plugin ahead of time

https://github.com/Olical/nvim-local-fennel[nvim-local-fennel] and the experimental https://github.com/Olical/conjure-sourcery[conjure-sourcery] should be good examples of Fennel based plugins (I hope so, I wrote them), here's how to create something new.

We'll start by fetching the `dep.sh` helper script which we'll use to clone and update Aniseed. It can be used for repos other than Aniseed, feel free to reuse it.

[source,bash]
----
mkdir -p scripts
curl https://raw.githubusercontent.com/Olical/aniseed/master/scripts/dep.sh -o scripts/dep.sh
chmod +x scripts/dep.sh
----

Now let's clone Aniseed into `deps/aniseed`, be sure to `.gitignore` the `deps` directory. I keep my `dep.sh` calls in my `Makefile` so I can run `make deps` to synchronise anything that's required.

[source,bash]
----
scripts/dep.sh Olical aniseed vX.Y.Z # insert latest version
----

Now let's add a small program to `fnl/my-plugin/init.fnl`.

[source,clojure]
----
(module my-plugin.init)

(print "Hello, World!")
----

We can compile the plugin using `deps/aniseed/scripts/compile.sh` which will write into the `lua` directory, you should commit that output so that users of your plugin don't have to know it was ever written in Fennel in the first place.

Users can call into your plugin however and whenever they choose or you can add some sort of startup hook into `plugin/my-plugin.vim`.

[source,viml]
----
lua require('my-plugin.init')

" Prints: Hello, World!
----

== Using Aniseed at runtime in a plugin

I've only shown how to use Aniseed at compile time, there's one extra step involved when you want to use Aniseed in the runtime of your plugin. You can use `deps/aniseed/scripts/embed.sh` to copy Aniseed's Lua into your Lua directory under a directory prefix.

The code will be modified to add a prefix that keeps this version of Aniseed local to your plugin. This technique allows multiple plugins to carry their own copies of Aniseed with them without any conflicts or inconsistencies.

[source,bash]
----
deps/aniseed/scripts/embed.sh aniseed my-plugin
----

We can then refer to our Aniseed copy from `my-plugin.init`.

[source,clojure]
----
(module my-plugin.init
  {require {core my-plugin.aniseed.core}})

(core.pr {:msg "Hello, World!"})
----

== An example Makefile

[source,make]
----
.PHONY: deps compile

deps:
	scripts/dep.sh Olical aniseed vX.Y.Z # insert latest version

compile:
	rm -rf lua
	deps/aniseed/scripts/compile.sh
	deps/aniseed/scripts/embed.sh aniseed nvim-local-fennel
----

== Testing

TODO

== Unlicenced

The following files are excluded from my license and ownership:

 * `lua/aniseed/deps/fennel.lua`
 * `lua/aniseed/deps/fennelview.lua`
 * `lua/aniseed/deps/nvim.lua`

These files come from https://fennel-lang.org/[Fennel] and https://github.com/norcalli/nvim.lua[nvim.lua], *I did not write them*, all other files are from me and unlicenced. The aforementioned files should be considered under their respective project licences. They are copied into this repo to allow the plugin to work with systems that don't support symlinks correctly.

Find the full http://unlicense.org/[unlicense] in the `UNLICENSE` file, but here's a snippet.

____
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.
____
