= Aniseed

== Sweeter Neovim with Fennel

Write https://fennel-lang.org/[Fennel] code and have https://neovim.io/[Neovim] compile and execute it via Lua. Configure and control your Neovim through the wonders of Lisp!

This is mostly an experiment to see if I can replace my Neovim configuration in my https://github.com/Olical/dotfiles[dotfiles] as well as parts of https://github.com/Olical/conjure[Conjure] with Fennel.

Your code is compiled ahead of time into Lua only if it has changed since you last compiled it.

== Installation

Use your favourite plugin manager, I highly recommend https://github.com/junegunn/vim-plug[vim-plug] if you don't have one.

_Please_ pin the plugin to a tag then subscribe to new releases through the GitHub UI. I'd hate to accidentally break your entire configuration through a bad release or breaking change. I follow https://semver.org/[semver] any breaking changes will incur a major version bump.

[source,viml]
----
Plug 'Olical/aniseed', { 'tag': 'v0.0.0' }
----

== Compiling ahead of time

We can compile a single Fennel file to Lua through the `aniseed.compile` module.

[source,viml]
----
lua require("aniseed.compile").file("config.fnl", "config.lua")
----

You'll probably want to compile your plugin or configuration's entire Fennel collection to Lua in one go though, for that, that's `glob`.

[source,viml]
----
lua require("aniseed.compile").glob("**/*.fnl", "fnl", "lua")
----

This will compile all Fennel files found under the `fnl` directory into Lua and spit them out into the `lua` directory under the same directory structures as their source.

These functions will _not_ compile the files they're given unless the source is newer than the destination. If you wish to bypass this check you can pass an `opts` of `{force = true}` to either function as the last argument.

[source,viml]
----
lua require("aniseed.compile").file("config.fnl", "config.lua", {force = true})
----

== Evaluating with mappings

Ahead of time compiling covers most bases, but if you've ever written a Lisp you know how great REPL integration is. Aniseed provides a level of interactive evaluation, it's not quite https://github.com/Olical/conjure[Conjure] but it's still useful.

Given a simple Fennel program...

TODO

== Extras

=== Module reloading

TODO

=== Clojure inspired utility functions

TODO

== Development

Aniseed is written in Fennel and compiled to Lua by the `Makefile` (please read it before executing it!), the compiled files are committed to the repository. Bear this in mind when considering a contribution!

If you have https://github.com/embear/vim-localvimrc[vim-localvimrc] installed you'll have access to the mappings mentioned above (check out `.lvimrc`). By using these you can tweak Aniseed's source then try your changes out without restarting Neovim.

You can use `make test` to ensure the Fennel files in the `test` directory can be compiled and executed without error. It's a _very_ light test that won't catch much but it's better than nothing as a high level smoke test.

== Unlicenced

Find the full http://unlicense.org/[unlicense] in the `UNLICENSE` file, but here's a snippet.

____
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.
____
