= Aniseed

Easily write configuration or plugins for https://neovim.io/[Neovim] in https://fennel-lang.org/[Fennel], a Lisp that compiles to Lua.

This is aimed at people who want to extend Neovim interactively with a Lisp as you would Emacs without requiring any extra processes or remote plugins. Code is evaluated as you edit like in a Clojure with https://github.com/Olical/conjure[Conjure].

It provides the tools you need to compile, run, inspect and develop programs with Fennel. It includes a set of macros to make defining and depending on modules far more like Clojure than Lua. No more remembering to put values in a table at the bottom of the file!

[source,clojure]
----
(module my-module
  {require {core aniseed.core
            nvim aniseed.nvim}})

(def- some-private-value 2)

(defn- some-private-fn [x]
  (* x some-private-value))

(defn a-public-fn [x]
  (-> x
      (some-private-fn)
      (core.inc)))

(comment
  (a-public-fn 10) ;; => 21
  (some-private-fn 10) ;; => 20
  (set nvim.g.hello "world!"))
----

Aniseed allows you to evaluate any form in this source code to build up your module dynamically with a constant REPL based flow. Once the buffer, file or forms have been evaluated you can even call the function from Lua and Vim Script.

[source,viml]
----
lua print(require("my-module")["a-public-fn"](10))
" Prints: 21

echo g:hello
" Prints: world!
----

== Installation

Use your favourite plugin manager, I recommend https://github.com/junegunn/vim-plug[vim-plug] if you don't have one already.

[source,viml]
----
Plug 'Olical/aniseed', { 'tag': 'v3.0.0' }

" For Fennel code highlighting (based on Clojure).
Plug 'bakpakin/fennel.vim'

" Used by the evaluation mappings.
Plug 'guns/vim-sexp'

" Highly recommended if you're going to use vim-sexp.
Plug 'tpope/vim-sexp-mappings-for-regular-people'

" Set up the Aniseed commands and mappings.
lua require("aniseed.mapping").init()
----

The reliance on `vim-sexp` will be replaced by integration with https://github.com/Olical/conjure[Conjure] once I've finished rewriting it with Aniseed. Conjure, with the help of Aniseed, will become a generic suite for working with Lisps in Neovim.

== Unlicenced

The following files are excluded from my license and ownership:

 * `lua/aniseed/deps/fennel.lua`
 * `lua/aniseed/deps/fennelview.lua`
 * `lua/aniseed/deps/nvim.lua`

These files come from https://fennel-lang.org/[Fennel] and https://github.com/norcalli/nvim.lua[nvim.lua], *I did not write them*, all other files are from me and unlicenced. The aforementioned files should be considered under their respective project licences. They are copied into this repo to allow the plugin to work with systems that don't support symlinks correctly.

Find the full http://unlicense.org/[unlicense] in the `UNLICENSE` file, but here's a snippet.

____
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.
____

=== NOTES

delet dis

https://oli.me.uk/neovim-configuration-and-plugins-in-fennel-lisp/
https://fennel-lang.org/
https://neovim.io/
https://github.com/Olical/dotfiles
https://github.com/Olical/conjure
https://github.com/Olical/conjure-sourcery
https://github.com/Olical/nvim-local-fennel
https://github.com/junegunn/vim-plug
https://semver.org/
