= Aniseed

== Unlicenced

The following files are excluded from my license and ownership:

 * `lua/aniseed/deps/fennel.lua`
 * `lua/aniseed/deps/fennelview.lua`
 * `lua/aniseed/deps/nvim.lua`

These files come from https://fennel-lang.org/[Fennel] and https://github.com/norcalli/nvim.lua[nvim.lua], *I did not write them*, all other files are from me and unlicenced. The aforementioned files should be considered under their respective project licences. They are copied into this repo to allow the plugin to work with systems that don't support symlinks correctly.

Find the full http://unlicense.org/[unlicense] in the `UNLICENSE` file, but here's a snippet.

____
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.
____

=== NOTES

delet dis

https://oli.me.uk/neovim-configuration-and-plugins-in-fennel-lisp/
https://fennel-lang.org/
https://neovim.io/
https://github.com/Olical/dotfiles
https://github.com/Olical/conjure
https://github.com/Olical/conjure-sourcery
https://github.com/Olical/nvim-local-fennel
https://github.com/junegunn/vim-plug
https://semver.org/
